title: "Nikita Burmistrov"
email: nikita@burmistrov.tech
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: nburmistrov
github_username:  nburmistrov
telegram_username: nburmistrov

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll_picture_tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

# see http://rbuchberger.github.io/jekyll_picture_tag/users/configuration/
picture:
  source: assets/images/
  output: generated/
  relative_url: true
  suppress_warnings: false

paginate: 8
paginate_path: "page/:num"
excerpt_separator: <!--more-->

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false