title: "Nikita Burmistrov"
email: nikita@burmistrov.tech
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: "https://www.burmistrov.tech" 
linkedin_username: burmistrov-tech
github_username:  burmistrov-tech
telegram_username: burmistrov_tech

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll_picture_tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

# see http://rbuchberger.github.io/jekyll_picture_tag/users/configuration/
picture:
  source: assets/images/
  output: generated/
  relative_url: true
  suppress_warnings: false

paginate: 5
paginate_path: "page/:num"
excerpt_separator: <!--more-->

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false

feed:
  title: https://www.burmistrov.tech
  subtitle: Nikita Burmistrov | Blog
  path: rss.xml